In [1]:
import pandas as pd
import numpy as np
from math import sin, cos, sqrt, atan2, radians

In [2]:
#Constants
R = 6373.0 # earth's radius

In [3]:
data = pd.read_csv('../data/AB_NYC_2019.csv')
data_sampled = data.sample(n=100)

In [4]:
#data.head()
data_sampled.sort_values(by=['id'], inplace=True)
data_sampled.head()
#print(data_sampled)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
46,12937,"1 Stop fr. Manhattan! Private Suite,Landmark B...",50124,Orestes,Queens,Long Island City,40.74771,-73.94740,Private room,130,3,248,2019-07-01,2.25,1,215
504,179741,Spring & Mulberry 2 Bedroom Apartment,314941,Tony,Manhattan,Nolita,40.72133,-73.99666,Entire home/apt,300,1,6,2019-06-28,0.06,3,115
1213,517626,Above Graham stop - L train,2438262,Walker,Brooklyn,Williamsburg,40.71577,-73.94084,Private room,95,1,10,2014-12-03,0.14,1,0
1389,616585,Great house in Williamsburg,10889,Bob,Brooklyn,Williamsburg,40.72091,-73.96133,Entire home/apt,250,3,25,2017-11-21,0.30,2,188
1749,791452,Jazzy condo in Riverdale -fresh grown veggies,2556784,Claudia,Bronx,Fieldston,40.88757,-73.90522,Entire home/apt,60,1,25,2019-07-05,0.67,1,311

In [5]:
def measure_distance(lat0, lon0, lat1, lon1) :
    
    lat0 = radians(lat0)
    lon0 = radians(lon0)
    lat1 = radians(lat1)
    lon1 = radians(lon1)
    
    dlat = lat1 - lat0
    dlon = lon1 - lon0

    a = sin(dlat / 2)**2 + cos(lat0) * cos(lat1) * sin(dlon / 2)**2
    c = 2 * atan2(sqrt(a), sqrt(1 - a))
    
    return R * c # return distance in km

In [6]:
print(measure_distance(data_sampled['latitude'][19], data_sampled['longitude'][19], data_sampled['latitude'][372], data_sampled['longitude'][372]))
print(data.shape)
#print(data_sampled.shape)

KeyError: 19

In [ ]:
distance_matrix = np.zeros((data_sampled.shape[0], data_sampled.shape[0]))
for i in range(data_sampled.shape[0]):
    for j in range(data_sampled.shape[0]):
        distance_matrix[i, j] = measure_distance(data_sampled['latitude'][i],
                                                 data_sampled['longitude'][i],
                                                 data_sampled['latitude'][j],
                                                 data_sampled['longitude'][j])

In [ ]:
print(distance_matrix)